version: '3'
services:
  main-app:
    build:
      context: ./main-app
    image: elasticapm-main-app-image
    ports:
      - "3002:3002"
    volumes:
      - ./main-app/FlightFare_Dataset.xlsx:/app/FlightFare_Dataset.xlsx
      - ./main-app/flight_rf.pkl:/app/flight_rf.pkl
    depends_on:
      - prediction-service
      - flight-compare-service  # Corrected the service name here

  prediction-service:
    build:
      context: ./prediction-service
    image: elasticapm-prediction-image
    ports:
      - "3001:3001"
    volumes:
      - ./prediction-service/FlightFare_Dataset.xlsx:/app/FlightFare_Dataset.xlsx
      - ./prediction-service/flight_rf.pkl:/app/flight_rf.pkl

  flight-compare-service:
    build:
      context: ./flight-compare-service
    image: elasticapm-flight-compare-image
    ports:
      - "3003:3003"
    volumes:
      - ./flight-compare-service/FlightFare_Dataset.xlsx:/app/FlightFare_Dataset.xlsx
