apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app-container
        image: hunain33/main-app:0.0.1.RELEASE  # Replace with the actual image name and version
        ports:
        - containerPort: 3002
