apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
      - name: prediction-container
        image: hunain33/prediction:0.0.1.RELEASE
        ports:
        - containerPort: 3001
