apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  # Use ClusterIP service type for internal communication within the cluster
  type: ClusterIP
