# Use the official Python image as the base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the entire contents of the prediction-service directory into the container at /app
COPY ../main-app/ .

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the required libraries using pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the main_app.py file into the container
COPY main_app.py .

# Expose the port on which the Flask app will run
EXPOSE 3002

# Command to start the Flask app
CMD ["python", "main_app.py"]
