# Use the official Python image as the base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the entire contents of the flight-compare-service directory into the container at /app
COPY . /app

# Copy only the necessary files to the container
COPY flight_comparison_service.py .
COPY FlightFare_Dataset.xlsx .


# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the required libraries using pip
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port on which the Flask app will run
EXPOSE 3003

# Command to start the Flask app
CMD ["python", "flight_comparison_service.py"]
